/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanjutan;

/**
 *
 * @author PC
 */
public class BIO extends javax.swing.JFrame {

    /**
     * Creates new form BIO
     */
    public BIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uwu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        ABSEN = new javax.swing.JLabel();
        KELAS = new javax.swing.JLabel();
        JURUSAN = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        jurusan = new javax.swing.JRadioButton();
        Jurusan = new javax.swing.JRadioButton();
        absen = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JComboBox();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("BIODATA SISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(218, 7, 180, 17);

        NAMA.setText("NAMA");
        jPanel1.add(NAMA);
        NAMA.setBounds(31, 40, 60, 16);

        ABSEN.setText("ABSEN");
        jPanel1.add(ABSEN);
        ABSEN.setBounds(31, 74, 60, 16);

        KELAS.setText("KELAS");
        jPanel1.add(KELAS);
        KELAS.setBounds(31, 114, 60, 16);

        JURUSAN.setText("JURUSAN");
        jPanel1.add(JURUSAN);
        JURUSAN.setBounds(31, 157, 60, 16);

        ALAMAT.setText("ALAMAT");
        jPanel1.add(ALAMAT);
        ALAMAT.setBounds(31, 200, 60, 16);

        uwu.add(jurusan);
        jurusan.setText("TKJ");
        jPanel1.add(jurusan);
        jurusan.setBounds(291, 153, 49, 25);

        uwu.add(Jurusan);
        Jurusan.setText("RPL");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(200, 153, 49, 25);
        jPanel1.add(absen);
        absen.setBounds(163, 71, 300, 22);
        jPanel1.add(nama);
        nama.setBounds(163, 37, 300, 22);

        kelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        jPanel1.add(kelas);
        kelas.setBounds(188, 111, 175, 22);

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat);
        alamat.setBounds(158, 197, 305, 22);

        jButton1.setText("EXIT");
        jPanel1.add(jButton1);
        jButton1.setBounds(299, 256, 59, 25);

        jButton2.setText("SEND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(191, 256, 63, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\20191101_134718.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 460);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String NAMA = nama.getText();
        String ABSEN =absen.getText();
        String KELAS = kelas.getSelectedItem().toString();
        String JURUSAN = "";
        String ALAMAT = alamat.getText();
        
        if (Jurusan.isSelected()) {
            JURUSAN = "RPL";
        } else if (jurusan.isSelected()) {
            JURUSAN = "TKJ";
        }
        if (kelas.getSelectedItem() == "X RPL 1") {
        
        } 
        if (kelas.getSelectedItem() == "X RPL 2") {
            
        } 
        if (kelas.getSelectedItem() == "X RPL 3") {
            
        }
        if (kelas.getSelectedItem() == "X RPL 4") {
            
        }
        if (kelas.getSelectedItem() == "X RPL 5") {
            
        }
        if (kelas.getSelectedItem() == "X RPL 6") {
            
        } 
        if (kelas.getSelectedItem() == "X RPL 7") {
            
        }
        if (kelas.getSelectedItem() == "X TKJ 1") {
            
        } 
        if (kelas.getSelectedItem() == "X TKJ 2") {
            
        } 
        if (kelas.getSelectedItem() == "X TKJ 3") {
            
        } 
        if (kelas.getSelectedItem() == "X TKJ 4") {
            
        }
        if (kelas.getSelectedItem() == "X TKJ 5") {
            
        }
        if (kelas.getSelectedItem() == "X TKJ 6") {
            
        }
        new Frame2(NAMA,ABSEN,KELAS,JURUSAN,ALAMAT).setVisible(true);
            
        
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABSEN;
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JLabel JURUSAN;
    private javax.swing.JRadioButton Jurusan;
    private javax.swing.JLabel KELAS;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField absen;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jurusan;
    private javax.swing.JComboBox kelas;
    private javax.swing.JTextField nama;
    private javax.swing.ButtonGroup uwu;
    // End of variables declaration//GEN-END:variables
}
