/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbogui;

/**
 *
 * @author PC
 */
public class KALKULATOR extends javax.swing.JFrame {

    /**
     * Creates new form KALKULATOR
     */
    public KALKULATOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bilangan2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bilangan1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("KALKULATOR SEDERHANA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(209, 25, 149, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 478, 0);

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("KALKULATOR SEDERHANA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(161, 20, 160, 16);

        jLabel3.setText("BILANGAN 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 160, 80, 40);
        getContentPane().add(Bilangan2);
        Bilangan2.setBounds(190, 160, 110, 50);

        jLabel4.setText("BILANGAN 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(81, 70, 80, 40);
        getContentPane().add(Bilangan1);
        Bilangan1.setBounds(190, 70, 110, 50);

        jLabel5.setText("OPERASI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(211, 220, 60, 16);

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 250, 79, 40);

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 250, 80, 40);

        jButton3.setText(":");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 250, 79, 40);

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 250, 79, 40);

        jLabel6.setText("HASIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 300, 40, 16);
        getContentPane().add(Hasil);
        Hasil.setBounds(180, 320, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Bil1 = Integer.parseInt(Bilangan1.getText());
        int Bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = Bil1*Bil2;
         Hasil.setText(String.valueOf(hasil));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double Bil1 = Double.parseDouble(Bilangan1.getText());
        double Bil2 = Double.parseDouble(Bilangan2.getText());
        double hasil2 = Bil1/Bil2;
        Hasil.setText(String.valueOf(hasil2));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int Bil1 = Integer.parseInt(Bilangan1.getText());
        int Bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil3 = Bil1+Bil2;
         Hasil.setText(String.valueOf(hasil3));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Bil1 = Integer.parseInt(Bilangan1.getText());
        int Bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil4 = Bil1-Bil2;
         Hasil.setText(String.valueOf(hasil4));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KALKULATOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bilangan1;
    private javax.swing.JTextField Bilangan2;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
