/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UjiKebolehan;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class KEBOLEHAN extends javax.swing.JFrame {

    /**
     * Creates new form KEBOLEHAN
     */
    public KEBOLEHAN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BERAT = new javax.swing.JLabel();
        BERAT1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        ideal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Perempuan = new javax.swing.JRadioButton();
        Laki = new javax.swing.JRadioButton();
        coba = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        PROSES = new javax.swing.JButton();
        jk = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BERAT3 = new javax.swing.JLabel();
        Hasil2 = new javax.swing.JTextField();
        Hasil1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(146, 13, 120, 15);

        NAMA.setText("NAMA");
        jPanel1.add(NAMA);
        NAMA.setBounds(12, 42, 100, 16);

        jLabel3.setText("TINGGI BADAN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 88, 100, 16);

        BERAT.setText("BERAT BADAN");
        jPanel1.add(BERAT);
        BERAT.setBounds(12, 134, 100, 16);

        BERAT1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        BERAT1.setForeground(new java.awt.Color(255, 255, 255));
        BERAT1.setText("HASIL DIAGNOSA KESEHATAN ");
        jPanel1.add(BERAT1);
        BERAT1.setBounds(110, 300, 210, 15);
        jPanel1.add(Nama);
        Nama.setBounds(146, 36, 250, 28);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(146, 82, 60, 28);
        jPanel1.add(ideal);
        ideal.setBounds(220, 258, 80, 22);

        jLabel2.setText("Cm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(211, 88, 30, 16);

        jLabel4.setText("Kg");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 260, 30, 20);

        Perempuan.setText("PEREMPUAN");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });
        jPanel1.add(Perempuan);
        Perempuan.setBounds(146, 174, 99, 25);

        Laki.setText("LAKI-LAKI");
        jPanel1.add(Laki);
        Laki.setBounds(249, 174, 83, 25);

        coba.setText("COBA LAGI");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        jPanel1.add(coba);
        coba.setBounds(180, 220, 100, 25);

        EXIT.setText("KELUAR");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(320, 220, 77, 25);

        PROSES.setText("HITUNG");
        PROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROSESActionPerformed(evt);
            }
        });
        jPanel1.add(PROSES);
        PROSES.setBounds(50, 220, 77, 25);

        jk.setText("JENIS KELAMIN");
        jPanel1.add(jk);
        jk.setBounds(12, 178, 100, 16);
        jPanel1.add(Berat);
        Berat.setBounds(146, 128, 60, 28);

        jLabel5.setText("Kg");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(211, 134, 30, 16);

        BERAT3.setForeground(new java.awt.Color(255, 255, 255));
        BERAT3.setText("BERAT BADAN IDEAL ANDA ADALAH ");
        jPanel1.add(BERAT3);
        BERAT3.setBounds(10, 260, 230, 16);
        jPanel1.add(Hasil2);
        Hasil2.setBounds(10, 370, 420, 40);
        jPanel1.add(Hasil1);
        Hasil1.setBounds(10, 320, 420, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerempuanActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
      
        
    }//GEN-LAST:event_cobaActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        dispose();
    }//GEN-LAST:event_EXITActionPerformed

    private void PROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROSESActionPerformed
        // TODO add your handling code here:
        try{
        int tinggi = Integer.parseInt(Tinggi.getText());
        int berat = Integer.parseInt(Berat.getText());
        String nama = Nama.getText();
        int Ideal = 0;
        if(Perempuan.isSelected()){
            Ideal = tinggi-100;
        } else if(Laki.isSelected()){
           Ideal = tinggi - 104;
        }
        String temp = Integer.toString(Ideal);
        if(Ideal < berat){
            ideal.setText(temp);
            Hasil1.setText("MON MAAF "+nama +", hmm...Sepertinya Anda Overweight : (");
            Hasil2.setText("PERBANYAK OLAHRAGA DAN HINDARI MAKANAN BERKOLESTEROL");
        }else if(Ideal > berat){
            ideal.setText(temp);
            Hasil1.setText("MON MAAF "+nama +", hmm...Sepertinya Anda Underweight : (");
            Hasil2.setText("PERBANYAK MENGONSUMSI MAKANAN BERKARBOHIDRAT");
        }else{
            ideal.setText(temp);
            Hasil1.setText("HALO "+nama +", GOOD JOB BERAT BADAN ANDA SUDAH IDEAL : (");
            Hasil2.setText("TETAP BEROLAHRAGA DAN JAGA POLA MAKAN"); 
        
    } 
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "KOTAK INPUT BELUM TERISI PENUH : LENGKAPI", "MESSAGE",
                JOptionPane.WARNING_MESSAGE);
    }       
    }//GEN-LAST:event_PROSESActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KEBOLEHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KEBOLEHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KEBOLEHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KEBOLEHAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KEBOLEHAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BERAT;
    private javax.swing.JLabel BERAT1;
    private javax.swing.JLabel BERAT3;
    private javax.swing.JTextField Berat;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField Hasil1;
    private javax.swing.JTextField Hasil2;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton PROSES;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton coba;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jk;
    // End of variables declaration//GEN-END:variables
}
