/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbogui;

/**
 *
 * @author PC
 */
public class PENILAIAN extends javax.swing.JFrame {

    /**
     * Creates new form PENILAIAN
     */
    public PENILAIAN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        ABSEN = new javax.swing.JTextField();
        MATPEL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NILAI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        matpel = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(119, 7, 292, 0);

        jLabel1.setText("PENILAIAN SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(168, 15, 120, 16);

        NAMA.setText("NAMA");
        getContentPane().add(NAMA);
        NAMA.setBounds(19, 38, 70, 22);

        ABSEN.setText("ABSEN");
        getContentPane().add(ABSEN);
        ABSEN.setBounds(19, 67, 70, 22);

        MATPEL.setText("MATPEL");
        getContentPane().add(MATPEL);
        MATPEL.setBounds(19, 96, 70, 22);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(12, 0, 397, 0);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(null);

        NILAI.setText("NILAI ");
        jPanel3.add(NILAI);
        NILAI.setBounds(20, 127, 70, 22);

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(161, 167, 79, 25);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(59, 210, 290, 115);

        nama.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(nama);
        nama.setBounds(134, 39, 215, 22);

        absen.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.add(absen);
        absen.setBounds(134, 68, 215, 22);

        matpel.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.add(matpel);
        matpel.setBounds(134, 97, 215, 22);

        nilai.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.add(nilai);
        nilai.setBounds(134, 127, 215, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 410, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String NAMA = nama.getText();
        String ABSEN = absen.getText();
        String MATPEL = matpel.getText();
        int NILAI = Integer.valueOf(nilai.getText());
        String ket = "";
        if (NILAI < 75) {
            ket = "Keterangan \t: TIDAK LULUS";
        } else if ((NILAI >= 75) && (NILAI == 100)) {
            ket = "Keterangan \t: UYE LULUS";
        } else if (NILAI == 100) {
            ket = "Keterangan \t: WOW Amazing";
        }
        TA.setText("NAMA \t:" + NAMA + "\n"
                + "ABSEN  \t:" + ABSEN + "\n"
                + "MATPEL \t:" + MATPEL + "\n"
                + "NILAI  \t:" + NILAI + "\n"
                + ket);

    
    }//GEN-LAST:event_jButton1ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PENILAIAN.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PENILAIAN.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PENILAIAN.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PENILAIAN.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PENILAIAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ABSEN;
    private javax.swing.JTextField MATPEL;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NILAI;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField absen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField matpel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
