/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAT2LAN;

/**
 *
 * @author PC
 */
import javax.swing.table.DefaultTableModel;
public class TabelBiodata extends javax.swing.JFrame {

    /**
     * Creates new form TabelBiodata
     */
    public TabelBiodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KELAS = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SEKOLAH = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Sekolah = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Kelas = new javax.swing.JComboBox();
        exit = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 13)); // NOI18N
        jLabel1.setText("TABEL BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(226, 13, 150, 16);

        NAMA.setText("NAMA");
        jPanel1.add(NAMA);
        NAMA.setBounds(73, 50, 70, 16);

        jLabel3.setText(":");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 50, 5, 16);

        KELAS.setText("KELAS");
        jPanel1.add(KELAS);
        KELAS.setBounds(73, 97, 70, 16);

        jLabel5.setText(":");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 97, 5, 16);

        ALAMAT.setText("ALAMAT");
        jPanel1.add(ALAMAT);
        ALAMAT.setBounds(73, 141, 70, 16);

        jLabel7.setText(":");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 141, 5, 16);

        SEKOLAH.setText("SEKOLAH");
        jPanel1.add(SEKOLAH);
        SEKOLAH.setBounds(73, 186, 70, 16);

        jLabel9.setText(":");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 186, 5, 16);
        jPanel1.add(Nama);
        Nama.setBounds(181, 47, 320, 30);
        jPanel1.add(Sekolah);
        Sekolah.setBounds(181, 183, 320, 30);
        jPanel1.add(Alamat);
        Alamat.setBounds(181, 138, 320, 30);

        Kelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6" }));
        jPanel1.add(Kelas);
        Kelas.setBounds(181, 94, 100, 22);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(354, 259, 59, 25);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(164, 259, 57, 25);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAMA", "KELAS", "ALAMAT", "SEKOLAH"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(73, 336, 452, 143);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String nama = Nama.getText();
        String kelas = Kelas.getSelectedItem().toString();
        String alamat = Alamat.getText();
        String sekolah = Sekolah.getText();
        if(Kelas.getSelectedItem()=="X RPL 1"){
        } if(Kelas.getSelectedItem()=="X RPL 2"){
        } if(Kelas.getSelectedItem()=="X RPL 3"){
        } if(Kelas.getSelectedItem()=="X RPL 4"){
        } if(Kelas.getSelectedItem()=="X RPL 5"){
        } if(Kelas.getSelectedItem()=="X RPL 6"){
        } if(Kelas.getSelectedItem()=="X RPL 7"){
        } if(Kelas.getSelectedItem()=="X TKJ 1"){
        } if(Kelas.getSelectedItem()=="X TKJ 2"){
        } if(Kelas.getSelectedItem()=="X TKJ 3"){
        } if(Kelas.getSelectedItem()=="X TKJ 4"){ 
        } if(Kelas.getSelectedItem()=="X TKJ 5"){
        } if(Kelas.getSelectedItem()=="X TKJ 6"){
            
        }
        //UNTUK MODEL TABEL
        DefaultTableModel model  = (DefaultTableModel) Table.getModel();
        model.addRow(new Object[]{Nama.getText(), Kelas.getSelectedItem(), Alamat.getText(), Sekolah.getText()});
    }//GEN-LAST:event_addActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JTextField Alamat;
    private javax.swing.JLabel KELAS;
    private javax.swing.JComboBox Kelas;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField Nama;
    private javax.swing.JLabel SEKOLAH;
    private javax.swing.JTextField Sekolah;
    private javax.swing.JTable Table;
    private javax.swing.JButton add;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
