/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbogui;

/**
 *
 * @author PC
 */
public class tugas extends javax.swing.JFrame {

    /**
     * Creates new form tugas
     */
    public tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HB1 = new javax.swing.JLabel();
        HB2 = new javax.swing.JLabel();
        HB3 = new javax.swing.JLabel();
        HB4 = new javax.swing.JLabel();
        DISKON = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        hb1 = new javax.swing.JTextField();
        hb2 = new javax.swing.JTextField();
        hb3 = new javax.swing.JTextField();
        hb4 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("PEMBAYARAN BARANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(142, 13, 150, 16);

        HB1.setText("HARGA BARANG 1");
        jPanel1.add(HB1);
        HB1.setBounds(12, 47, 115, 16);

        HB2.setText("HARGA BARANG 2");
        jPanel1.add(HB2);
        HB2.setBounds(12, 79, 115, 16);

        HB3.setText("HARGA BARANG 3");
        jPanel1.add(HB3);
        HB3.setBounds(12, 114, 115, 16);

        HB4.setText("HARGA BARANG 4");
        jPanel1.add(HB4);
        HB4.setBounds(12, 149, 115, 16);

        DISKON.setText("----- DISKON -----");
        jPanel1.add(DISKON);
        DISKON.setBounds(12, 181, 115, 16);

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(34, 210, 79, 25);

        jButton2.setText("KELUAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(268, 210, 77, 25);

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(155, 210, 71, 25);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(34, 253, 311, 133);
        jPanel1.add(hb1);
        hb1.setBounds(139, 41, 218, 22);
        jPanel1.add(hb2);
        hb2.setBounds(139, 76, 218, 22);
        jPanel1.add(hb3);
        hb3.setBounds(139, 111, 218, 22);
        jPanel1.add(hb4);
        hb4.setBounds(139, 146, 218, 22);
        jPanel1.add(Diskon);
        Diskon.setBounds(139, 175, 218, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int HB1 = Integer.parseInt(hb1.getText());
        int HB2 = Integer.parseInt(hb2.getText());
        int HB3 = Integer.parseInt(hb3.getText());
        int HB4 = Integer.parseInt(hb4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        int total = HB1+HB2+HB3+HB4;
        int totalharga = total - (total * diskon/100);
        TA.setText("HARGA 1: "+HB1+ "\nHARGA 2: "+HB2+ "\nHARGA 3: "+HB3+ "\nHARGA 4: "+HB4+ "\nDISKON: "+diskon+ "\nTOTAL HARGA: "+totalharga);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DISKON;
    private javax.swing.JTextField Diskon;
    private javax.swing.JLabel HB1;
    private javax.swing.JLabel HB2;
    private javax.swing.JLabel HB3;
    private javax.swing.JLabel HB4;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JTextField hb4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
