/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lat3;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class VOLUM extends javax.swing.JFrame {

    /**
     * Creates new form VOLUM
     */
    public VOLUM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PANJANG = new javax.swing.JLabel();
        LEBAR = new javax.swing.JLabel();
        TINGGI = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        HASIL = new javax.swing.JButton();
        jari = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        volume = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 320, 15);

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(null);

        PANJANG.setText("MASUKKAN PANJANG :");
        jPanel1.add(PANJANG);
        PANJANG.setBounds(12, 13, 132, 25);

        LEBAR.setText("MASUKKAN LEBAR     :");
        jPanel1.add(LEBAR);
        LEBAR.setBounds(12, 56, 132, 25);

        TINGGI.setText("MASUKKAN TINGGI    :");
        jPanel1.add(TINGGI);
        TINGGI.setBounds(12, 99, 132, 25);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(160, 90, 110, 30);
        jPanel1.add(Panjang);
        Panjang.setBounds(160, 10, 110, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(160, 10, 110, 30);
        jPanel1.add(Lebar);
        Lebar.setBounds(160, 50, 110, 30);

        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(170, 150, 77, 25);

        jLabel6.setText("Cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 100, 30, 16);

        jLabel7.setText("Cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 20, 30, 16);

        jLabel8.setText("Cm");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 60, 30, 16);

        jTabbedPane1.addTab("BALOK", jPanel1);

        jPanel2.setLayout(null);

        jLabel9.setText("MASUKKAN PANJANG SISI : ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 20, 170, 16);
        jPanel2.add(Sisi);
        Sisi.setBounds(40, 40, 110, 30);

        jLabel10.setText("Cm");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 50, 30, 16);

        HASIL.setText("volume");
        HASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HASILActionPerformed(evt);
            }
        });
        jPanel2.add(HASIL);
        HASIL.setBounds(40, 100, 90, 25);

        jTabbedPane1.addTab("KUBUS", jPanel2);

        jari.setLayout(null);

        jLabel11.setText("MASUKKAN PANJANG JARI-JARI :");
        jari.add(jLabel11);
        jLabel11.setBounds(20, 20, 210, 16);
        jari.add(r);
        r.setBounds(40, 40, 110, 30);

        jLabel12.setText("Cm");
        jari.add(jLabel12);
        jLabel12.setBounds(150, 50, 30, 16);

        volume.setText("volume");
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });
        jari.add(volume);
        volume.setBounds(50, 100, 90, 25);

        jTabbedPane1.addTab("BOLA", jari);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 440, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi =  Integer.parseInt(Lebar.getText());
        int Hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+Hasil, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_HitungActionPerformed

    private void HASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HASILActionPerformed
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        try{
            JOptionPane.showMessageDialog(null,"VOLUME KUBUS : "+HASIL, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HASILActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
       float jari;
       jari = Integer.parseInt(r.getText());
       float volume = (float)(4/3*3.14*jari*jari*jari);
       try{
            JOptionPane.showMessageDialog(null,"VOLUME BOLA : "+HASIL, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
       
       
    }//GEN-LAST:event_volumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOLUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOLUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOLUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOLUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOLUM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HASIL;
    private javax.swing.JButton Hitung;
    private javax.swing.JLabel LEBAR;
    private javax.swing.JTextField Lebar;
    private javax.swing.JLabel PANJANG;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JLabel TINGGI;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel jari;
    private javax.swing.JTextField r;
    private javax.swing.JButton volume;
    // End of variables declaration//GEN-END:variables
}
